repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.32.2
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit, pre-push]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
